### PR TITLE
SourceGithub plugin configuration docs

### PR DESCRIPTION
**Pull request by morgant**
Added new, detailed **SourceGithub** plugin configuration documentation. This also provides structure for additional plugin-specific configuration documentation in the `docs/` subdirectory.

### CODE REVIEW

**Comment by morgant** [comment]
Bump.

**Comment by dregad** [comment]
Sorry, I've been under the water... Will try to do this by end of week if I can.

**Comment by morgant** [comment]
Thanks and no worries!

**Comment by dregad** [comment]
Fixed in 93c9899f10e79ccff347aa0db67d86acb7e6844b and 2 subsequent commits. Many thanks for your contribution @morgant

**Comment by morgant** [comment]
Thanks!

**Pull request closed without merging**
