### PR TITLE
feature: Azure DevOps Service connection (initial commit)

### PR DESCRIPTION
**Pull request by stegrofan1jo**
I just needed some basic integration for Microsoft Azure DevOps Services repositories.
Maybe someon is interested in this functionality.

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution. 

May I kindly ask you to update the relevant documentation files to reference the new plugin ?

- [README](https://github.com/mantisbt-plugins/source-integration/blob/master/README.md)
- [Classes hierarchy](https://github.com/mantisbt-plugins/source-integration/blob/master/docs/Classes.md)
- if you can, providing a specific CONFIGURING document would be nice too.

**Comment by stegrofan1jo** [comment]
Sure, sorry that i forgot!

**Comment by ncourtiller** [comment]
I'm interested with this new functionality. May I ask whether this PR are going to be merge soon or if this is somehow scheduled ?
Thanks.

**Comment by dregad** [comment]
Not having access to an Azure setup, I can't test this, and it will be difficult for me to maintain and support it so I'll have to rely on community for that, but I have no objections with including it in the next release of the Framework.

If you have no objections, I'll change the version number from 0.0.1 to 1.0.0.

Thanks @stegrofan1jo for your contribution.

**Pull request closed without merging**
