### PR TITLE
Fixes #80

### LINKED ISSUE #80: Plugin assigns issues to non-developers
When the plugin picks up a commit by a user registered in the tracker, it resolves the issue and assigns it to that user, even if they are not developers.

Example http://www.mantisbt.org/bugs/view.php?id=16871

### PR DESCRIPTION
**Pull request by bright-tools**
Add a check upon bug closure as to the user's permissions with respect to the project prior to assigning the bug to them

### CODE REVIEW

**Comment by dregad** [comment]
I'm not sure this fully covers the issue. What happens if the user does not have access ?

**Comment by bright-tools** [comment]
Thanks for looking - could you explain what you mean a little?

It's intended that `access_has_project_level` is used to check the user's access against the required level for the project.  If the user doesn't have access to the project then `access_get_project_level` (called by `access_has_project_level`0 will return 0, meaning that the check will fail and the assignment of the handler_id should be skipped.

**Comment by dregad** [comment]
Which would potentially result in a resolved issue without assignment which, IMO, is conceptually wrong (although arguably better than assigning someone who is not allowed to handle issues).

**Comment by bright-tools** [comment]
Ah, understood.  So the better solution would be to also skip the resolving of the issue in addition to skipping the assignment?

**Comment by dregad** [comment]
That's what I was thinking, yes.

**Comment by bright-tools** [comment]
Thanks - I've had another go at the update (manually tested OK on my installation here).  Let me know if that's closer to the mark and if there's anything still missing.

**Comment by dregad** [comment]
I ended up implementing things in a slightly different way. Thanks for your contribution anyway !

**Pull request closed without merging**
