### PR TITLE
Add support for username and password entry / HTTP basic auth

### PR DESCRIPTION
**Pull request by wuttke**
Hi, I've added support myself - see corresponding issue #143. Was able to contribute German and English translations.

### CODE REVIEW

**Comment by elfuegobiz** [comment]
Please merge this to modern-ui branch,

**Comment by dregad** [comment]
@elfuegobiz I'm planning to cut an "official" modern UI release 2.0.0, up-to-date with all changes currently in master, hopefully by end of this week (if all goes according to plan).

**Comment by elfuegobiz** [comment]
Great, thank you!

**Comment by elfuegobiz** [comment]
@dregad special thanks for that all went according to plan =)

**Comment by dregad** [comment]
Well technically I missed the deadline by nearly 2 hours (and went to bed waaaaay too late ;) )

**Pull request closed without merging**
