### PR TITLE
Added parametter $7 to 'Bug Fixed Message Template' for bitbucket rep…

### PR DESCRIPTION
**Pull request by ms502040**
…o name

### CODE REVIEW

**Comment by dregad** [comment]
What is the difference between your new *reponame* parameter, and the existing $5 *repository name* ?

**Comment by ms502040** [comment]
in /plugin.php?page=Source/repo_manage_page&id=xx
$5 is name in mantis (name)
$7 is name on bitbucket, that is not same in ur settings (["bit_reponame"])
 u can make message for example:
Fix committed to $1 branch. <br>Revission: <a href="https://bitbucket.org/[user_name]/$7/commits/$2">revission</a><br>Time: $3<br>Changeset:<br>http://bt.z-web.eu/plugin.php?page=Source/view&id=$6<br>Commit message:<br>$4

**Comment by dregad** [comment]
OK, I see what you mean now. Nevertheless, I don't like the approach you're proposing, because `Source_Process_Changesets()` is a transversal function used by all VCS-specific plugins, and you're referencing `bit_reponame` which only exists in Bitbucket repos. 

That would not cause any errors since you check for existence of the array key prior to referencing it, but still it is not good design - I would prefer a solution that can be used with other plugins too (e.g. consider that SourceGihub and SourceGitlab use *hub_reponame* for the same information). IMO, the logic to handle VCS-specific parameters should be handled in the sub-plugin, not in the Source API.

**Comment by dregad** [comment]
@ms502040 if you're not planning to submit a corrected patch as per [my earlier comment](https://github.com/mantisbt-plugins/source-integration/pull/142#issuecomment-183231844), I will close this PR.

**Pull request closed without merging**
